let videofeed = [
    {
        main: [
            {
            title: '6 Pro tips from React Developers',
            thumbnail: 'www.minireel.come/192401940192/thumb',
            url: 'www.minireel.come/192401940192',
            description: 'Learn from the success—and failures—of React developers who’ve learned valuable lessons about the library. Here are 6 Pro Tips from React Developers.',
            publisher: 'Vue Mastery',
            publish: '02/27/2018',
            meta: 54903-32992-22,
            },
            {
            title: 'David Foster Wallace on Gen X, "Infinite Jest" and a life of writing (1996)',
            thumbnail: 'www.minireel.come/192401940192/thumb',
            url: 'www.minireel.come/192401940192',
            description: 'David Foster Wallace appeared on "The Connection" with Christopher Lydon on February 21, 1996 to promote "Infinite Jest". The interview turned up as we planned a radio show about that novel\'s Boston roots. Wallace talks addiction, generations, Boston AA, and more here; find out more at radioopensource.org, and subscribe to our podcast on iTunes.',
            publisher: 'James Larkin',
            publish: '03/26/2014',
            meta: 198903-23329-40,
            },
            {
            title: 'Deerhunter - live at Best Kept Secret 2018',
            thumbnail: 'www.minireel.come/192401940192/thumb',
            url: 'www.minireel.come/192401940192',
            description: 'Setlist: 0:00 Cover Me (Slowly)/Agoraphobia 5:35 Detournement 9:32 Revival 12:00 Futurism 14:53 What Happens To People 21:34 Death In Midsummer 26:35 Desire Lines 33:42 No One\'s Sleeping 38:25 Helicopter 45:29 Take Care 50:13 He Would Have Laughed De Amerikaanse band Deerhunter heeft er een handje van shows rond één album te bouwen. Dit flikten ze in 2015 met hun laatste album Fading Frontier op Le Guess Who?, en vandaag halen ze het trucje nog een keer uit. Maar nu tillen ze het naar het volgende niveau. Namelijk met de cassette The Double Dream of Spring waar slechts driehonderd exemplaren van zijn en niet online te vinden is. Lees alles over Best Kept Secret 2018 hier: bit.ly/3voor12BestKeptSecret Je hoort in 3voor12 Radio de allernieuwste muzikale trends, alternative tracks en de actualiteit van vandaag én morgen. Regelmatig zijn er artiesten te gast om te praten over hun nieuwe releases (en om ze te spelen, natuurlijk). Ook hoor je hier concertrecensies en de Je Weet Nooit Wat Je Krijgt-Request! Tune in: iedere maandag t/m donderdag van 21.00u - 00.00u.',
            publisher: '3voor12',
            publish: '06/12/2018',
            meta: 62930-1932-120,
            },
            {
            title: 'Carson Meets Anton | No Country For Old Men (2007)',
            thumbnail: 'www.minireel.come/192401940192/thumb',
            url: 'www.minireel.come/192401940192',
            description: 'No Country For Old Men (2007) - Joel and Ethan Coen - Anton and Carson Scene',
            publisher: 'Lost Theater',
            publish: '06/21/2016',
            meta: 8903-2345-40,
            },
            {
            title: 'The best combination of corners in the world? The Porsche Panamera on the on-road circuit in Leipzig',
            thumbnail: 'www.minireel.come/192401940192/thumb',
            url: 'www.minireel.come/192401940192',
            description: 'Accelerate your adrenaline on eleven world-famous corners: The Porsche on-road circuit in Leipzig is as unique as it is compelling! Designed by civil engineer Hermann Tilke. A tour with the Porsche Panamera Turbo S E-Hybrid Sport Turismo. Eleven sections of world-renowned race tracks were replicated and strung together on the Porsche on-road circuit in Leipzig. The “Corkscrew,” the “Parabolica” and the “Karussell” – each formation has its characteristic features. How does one master this extraordinary circuit? In 9:11 Magazine civil engineer Hermann Tilke guides through the most spectacular corners. The Porsche Panamera Turbo S E-Hybrid Sport Turismo cranks it up to 11 on the extraordinary circuit!',
            publisher: 'Porsche',
            publish: '03/11/2018',
            meta: 45903-32342-10,
            },
            {
            title: '88,000 tons of radioactive waste – and nowhere to put it',
            thumbnail: 'www.minireel.come/192401940192/thumb',
            url: 'www.minireel.come/192401940192',
            description: 'The United States produces 2,200 tons of nuclear waste each year…and no one knows what to do with it. The federal government has long promised, but never delivered, a safe place for nuclear power plants to store their spent fuel. This means that radioactive waste is piling up all over the country. We visited one of the worst places where the waste is stuck: a beachside power plant uncomfortably close to both San Diego and Los Angeles. And we asked the people in charge of the waste there: what happens now? Subscribe: http://bit.ly/2FqJZMl Like Verge Science on Facebook: http://bit.ly/2hoSuk Follow on Twitter: http://bit.ly/2Kr29B Follow on Instagram: https://goo.gl/7ZeLvX Read More: http://www.theverge.com Community guidelines: http://bit.ly/2D0hlAv Subscribe to Verge on YouTube for explainers, product reviews, technology news, and more: http://goo.gl/G5RXGs',
            publisher: 'Verge Science',
            publish: '06/28/2018',
            meta: 198903-39-3940,
            },
            {
            title: 'Where Does New York City\'s Trash Go? | Living City | The New York Times',
            thumbnail: 'www.minireel.come/192401940192/thumb',
            url: 'www.minireel.come/192401940192',
            description: 'New York City has one of the largest sanitation departments in the world, but, with declining landfills, we follow waste from sidewalks and garbage trucks to treatment facilities and upstate farms. Subscribe on YouTube: http://bit.ly/U8Ys7n New York City has the most complex waste management system in North America. This is the history of trash in New York City. Read the story: http://nyti.ms/1t0uIEp',
            publisher: 'The New York Times',
            publish: '09/25/2014',
            meta: 1903-39-40,
            },
            {
            title: 'Jim Carrey Impressions of Kevin Bacon & Wile E. Coyote on Johnny Carson\'s Tonight Show',
            thumbnail: 'www.minireel.come/192401940192/thumb',
            url: 'www.minireel.come/192401940192',
            description: 'Jim Carrey does funny impressions of famous people including Kevin Bacon and cartoon character Wile E. Coyote and impersonations of a scene from "Poltergeist" on "The Tonight Show Starring Johnny Carson" in 1991.  ',
            publisher: 'Johnny Carson',
            publish: '7/23/2011',
            meta: 9888833-22489-346,
            },
            {
            title: 'Seinfeld Bloopers - Julia Louis-Dreyfus 2',
            thumbnail: 'www.minireel.come/192401940192/thumb',
            url: 'www.minireel.come/192401940192',
            description: '',
            publisher: 'Anssi Purola',
            publish: '01/03/2010',
            meta: 8903-439-20,
            },
            {
            title: 'Ricky Gervais....67th Annual Golden Globes',
            thumbnail: 'www.minireel.come/192401940192/thumb',
            url: 'www.minireel.come/192401940192',
            description: 'All clips of Ricky Gervais from the 2010 67th Golden Globe Awards',
            publisher: 'Gervais',
            publish: '04/27/2015',
            meta: 2323203-324523-320,
            },
            {
            title: '6 Pro tips from React Developers',
            thumbnail: 'www.minireel.come/192401940192/thumb',
            url: 'www.minireel.come/192401940192',
            description: 'Learn from the success—and failures—of React developers who’ve learned valuable lessons about the library. Here are 6 Pro Tips from React Developers.',
            publisher: 'Vue Mastery',
            publish: '02/27/2018',
            meta: 54903-32992-22,
            },
            {
            title: 'David Foster Wallace on Gen X, "Infinite Jest" and a life of writing (1996)',
            thumbnail: 'www.minireel.come/192401940192/thumb',
            url: 'www.minireel.come/192401940192',
            description: 'David Foster Wallace appeared on "The Connection" with Christopher Lydon on February 21, 1996 to promote "Infinite Jest". The interview turned up as we planned a radio show about that novel\'s Boston roots. Wallace talks addiction, generations, Boston AA, and more here; find out more at radioopensource.org, and subscribe to our podcast on iTunes.',
            publisher: 'James Larkin',
            publish: '03/26/2014',
            meta: 198903-23329-40,
            },
            {
            title: 'Deerhunter - live at Best Kept Secret 2018',
            thumbnail: 'www.minireel.come/192401940192/thumb',
            url: 'www.minireel.come/192401940192',
            description: 'Setlist: 0:00 Cover Me (Slowly)/Agoraphobia 5:35 Detournement 9:32 Revival 12:00 Futurism 14:53 What Happens To People 21:34 Death In Midsummer 26:35 Desire Lines 33:42 No One\'s Sleeping 38:25 Helicopter 45:29 Take Care 50:13 He Would Have Laughed De Amerikaanse band Deerhunter heeft er een handje van shows rond één album te bouwen. Dit flikten ze in 2015 met hun laatste album Fading Frontier op Le Guess Who?, en vandaag halen ze het trucje nog een keer uit. Maar nu tillen ze het naar het volgende niveau. Namelijk met de cassette The Double Dream of Spring waar slechts driehonderd exemplaren van zijn en niet online te vinden is. Lees alles over Best Kept Secret 2018 hier: bit.ly/3voor12BestKeptSecret Je hoort in 3voor12 Radio de allernieuwste muzikale trends, alternative tracks en de actualiteit van vandaag én morgen. Regelmatig zijn er artiesten te gast om te praten over hun nieuwe releases (en om ze te spelen, natuurlijk). Ook hoor je hier concertrecensies en de Je Weet Nooit Wat Je Krijgt-Request! Tune in: iedere maandag t/m donderdag van 21.00u - 00.00u.',
            publisher: '3voor12',
            publish: '06/12/2018',
            meta: 62930-1932-120,
            },
            {
            title: 'Carson Meets Anton | No Country For Old Men (2007)',
            thumbnail: 'www.minireel.come/192401940192/thumb',
            url: 'www.minireel.come/192401940192',
            description: 'No Country For Old Men (2007) - Joel and Ethan Coen - Anton and Carson Scene',
            publisher: 'Lost Theater',
            publish: '06/21/2016',
            meta: 8903-2345-40,
            },
            {
            title: 'The best combination of corners in the world? The Porsche Panamera on the on-road circuit in Leipzig',
            thumbnail: 'www.minireel.come/192401940192/thumb',
            url: 'www.minireel.come/192401940192',
            description: 'Accelerate your adrenaline on eleven world-famous corners: The Porsche on-road circuit in Leipzig is as unique as it is compelling! Designed by civil engineer Hermann Tilke. A tour with the Porsche Panamera Turbo S E-Hybrid Sport Turismo. Eleven sections of world-renowned race tracks were replicated and strung together on the Porsche on-road circuit in Leipzig. The “Corkscrew,” the “Parabolica” and the “Karussell” – each formation has its characteristic features. How does one master this extraordinary circuit? In 9:11 Magazine civil engineer Hermann Tilke guides through the most spectacular corners. The Porsche Panamera Turbo S E-Hybrid Sport Turismo cranks it up to 11 on the extraordinary circuit!',
            publisher: 'Porsche',
            publish: '03/11/2018',
            meta: 45903-32342-10,
            },
            {
            title: '88,000 tons of radioactive waste – and nowhere to put it',
            thumbnail: 'www.minireel.come/192401940192/thumb',
            url: 'www.minireel.come/192401940192',
            description: 'The United States produces 2,200 tons of nuclear waste each year…and no one knows what to do with it. The federal government has long promised, but never delivered, a safe place for nuclear power plants to store their spent fuel. This means that radioactive waste is piling up all over the country. We visited one of the worst places where the waste is stuck: a beachside power plant uncomfortably close to both San Diego and Los Angeles. And we asked the people in charge of the waste there: what happens now? Subscribe: http://bit.ly/2FqJZMl Like Verge Science on Facebook: http://bit.ly/2hoSuk Follow on Twitter: http://bit.ly/2Kr29B Follow on Instagram: https://goo.gl/7ZeLvX Read More: http://www.theverge.com Community guidelines: http://bit.ly/2D0hlAv Subscribe to Verge on YouTube for explainers, product reviews, technology news, and more: http://goo.gl/G5RXGs',
            publisher: 'Verge Science',
            publish: '06/28/2018',
            meta: 198903-39-3940,
            },
            {
            title: 'Where Does New York City\'s Trash Go? | Living City | The New York Times',
            thumbnail: 'www.minireel.come/192401940192/thumb',
            url: 'www.minireel.come/192401940192',
            description: 'New York City has one of the largest sanitation departments in the world, but, with declining landfills, we follow waste from sidewalks and garbage trucks to treatment facilities and upstate farms. Subscribe on YouTube: http://bit.ly/U8Ys7n New York City has the most complex waste management system in North America. This is the history of trash in New York City. Read the story: http://nyti.ms/1t0uIEp',
            publisher: 'The New York Times',
            publish: '09/25/2014',
            meta: 1903-39-40,
            },
            {
            title: 'Jim Carrey Impressions of Kevin Bacon & Wile E. Coyote on Johnny Carson\'s Tonight Show',
            thumbnail: 'www.minireel.come/192401940192/thumb',
            url: 'www.minireel.come/192401940192',
            description: 'Jim Carrey does funny impressions of famous people including Kevin Bacon and cartoon character Wile E. Coyote and impersonations of a scene from "Poltergeist" on "The Tonight Show Starring Johnny Carson" in 1991.  ',
            publisher: 'Johnny Carson',
            publish: '7/23/2011',
            meta: 9888833-22489-346,
            },
            {
            title: 'Seinfeld Bloopers - Julia Louis-Dreyfus 2',
            thumbnail: 'www.minireel.come/192401940192/thumb',
            url: 'www.minireel.come/192401940192',
            description: '',
            publisher: 'Anssi Purola',
            publish: '01/03/2010',
            meta: 8903-439-20,
            },
            {
            title: 'Ricky Gervais....67th Annual Golden Globes',
            thumbnail: 'www.minireel.come/192401940192/thumb',
            url: 'www.minireel.come/192401940192',
            description: 'All clips of Ricky Gervais from the 2010 67th Golden Globe Awards',
            publisher: 'Gervais',
            publish: '04/27/2015',
            meta: 2323203-324523-320,
            },
        ]
    },
    {
        featured:[
            
        ]
    }
]

export default videofeed;
